// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// AUTO-GENERATED by scripts/gen-redactors.mts from native/shared/privacy/redactors.json. Do not
// edit: change redactors.json, then `npm run gen:redactors`.

extension Redactor {
    /// What replaces text that looks like a secret.
    static let placeholder = #"[redacted]"#

    /// Every redactor, in the order they are applied.
    static let all: [Redactor] = [
        // A private-key block, whole or cut off where the window ends.
        Redactor(name: #"private-key-block"#, pattern: #"-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----(?:[A-Za-z0-9+/=\s]*-----END [A-Z0-9 ]*PRIVATE KEY-----|[A-Za-z0-9+/=\s]*)"#, ignoreCase: false, replacement: #"[redacted]"#),
        // A JSON web token: three base64url parts, the first two JSON objects.
        Redactor(name: #"json-web-token"#, pattern: #"\beyJ[A-Za-z0-9_-]+\.eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+"#, ignoreCase: false, replacement: #"[redacted]"#),
        // "Bearer <token>", as an Authorization header has it. The word stays.
        Redactor(name: #"bearer-token"#, pattern: #"\b(Bearer\s+)[A-Za-z0-9._~+/=-]{16,}"#, ignoreCase: true, replacement: #"$1[redacted]"#),
        // The password in an address (scheme://user:password@host). The rest stays.
        Redactor(name: #"address-password"#, pattern: #"(\b[a-z][a-z0-9+.-]*://[^\s/:@]+:)[^\s/@]+(@)"#, ignoreCase: true, replacement: #"$1[redacted]$2"#),
        // A value given to a name that says it is secret (password=, api_key:, "token": "…"). The name stays. Only a value with a digit and at least 6 characters, so that "Password: required" stays.
        Redactor(name: #"named-value"#, pattern: #"((?:password|passwd|pwd|passphrase|secret|token|api[_-]?key|access[_-]?key|private[_-]?key|credentials?)["']?\s*[=:]\s*["']?)(?=[^\s"']*[0-9])[^\s"']{6,}"#, ignoreCase: true, replacement: #"$1[redacted]"#),
        // Keys starting "sk-" (several AI providers).
        Redactor(name: #"api-key-sk"#, pattern: #"\bsk-[A-Za-z0-9_-]{16,}"#, ignoreCase: false, replacement: #"[redacted]"#),
        // Payment provider keys (secret, restricted, publishable; live or test).
        Redactor(name: #"payment-key"#, pattern: #"\b(?:sk|rk|pk)_(?:live|test)_[A-Za-z0-9]{16,}"#, ignoreCase: false, replacement: #"[redacted]"#),
        // Webhook signing secrets.
        Redactor(name: #"webhook-secret"#, pattern: #"\bwhsec_[A-Za-z0-9]{16,}"#, ignoreCase: false, replacement: #"[redacted]"#),
        // GitHub tokens.
        Redactor(name: #"github-token"#, pattern: #"\bgh[pousr]_[A-Za-z0-9]{16,}"#, ignoreCase: false, replacement: #"[redacted]"#),
        // GitHub fine-grained tokens.
        Redactor(name: #"github-fine-grained-token"#, pattern: #"\bgithub_pat_[A-Za-z0-9_]{16,}"#, ignoreCase: false, replacement: #"[redacted]"#),
        // GitLab tokens.
        Redactor(name: #"gitlab-token"#, pattern: #"\bglpat-[A-Za-z0-9_-]{16,}"#, ignoreCase: false, replacement: #"[redacted]"#),
        // AWS access key ids.
        Redactor(name: #"aws-access-key-id"#, pattern: #"\b(?:AKIA|ASIA)[0-9A-Z]{16}\b"#, ignoreCase: false, replacement: #"[redacted]"#),
        // Google API keys.
        Redactor(name: #"google-api-key"#, pattern: #"\bAIza[0-9A-Za-z_-]{35}"#, ignoreCase: false, replacement: #"[redacted]"#),
        // Slack tokens.
        Redactor(name: #"slack-token"#, pattern: #"\bxox[abeprs]-[A-Za-z0-9-]{16,}"#, ignoreCase: false, replacement: #"[redacted]"#),
        // npm tokens.
        Redactor(name: #"npm-token"#, pattern: #"\bnpm_[A-Za-z0-9]{16,}"#, ignoreCase: false, replacement: #"[redacted]"#),
        // Hugging Face tokens.
        Redactor(name: #"hugging-face-token"#, pattern: #"\bhf_[A-Za-z0-9]{16,}"#, ignoreCase: false, replacement: #"[redacted]"#),
    ]
}
