# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
find_program(VOICE_CARGO cargo REQUIRED)
set(VOICE_RUST_SOURCE "${CMAKE_CURRENT_LIST_DIR}")
if(WIN32)
  if(CMAKE_GENERATOR_PLATFORM STREQUAL "ARM64")
    set(VOICE_RUST_TARGET aarch64-pc-windows-msvc)
  elseif(CMAKE_GENERATOR_PLATFORM STREQUAL "x64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "AMD64|x86_64")
    set(VOICE_RUST_TARGET x86_64-pc-windows-msvc)
  else()
    message(FATAL_ERROR "Unsupported Windows Rust architecture")
  endif()
  set(VOICE_RUST_ARCHIVE tabmail_voice_core.lib)
elseif(APPLE)
  if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64")
    set(VOICE_RUST_TARGET aarch64-apple-darwin)
  else()
    set(VOICE_RUST_TARGET x86_64-apple-darwin)
  endif()
  set(VOICE_RUST_ARCHIVE libtabmail_voice_core.a)
else()
  if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64")
    set(VOICE_RUST_TARGET aarch64-unknown-linux-gnu)
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64")
    set(VOICE_RUST_TARGET x86_64-unknown-linux-gnu)
  else()
    message(FATAL_ERROR "Unsupported Linux Rust architecture")
  endif()
  set(VOICE_RUST_ARCHIVE libtabmail_voice_core.a)
endif()
set(VOICE_RUST_OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/rust/${VOICE_RUST_TARGET}/release/${VOICE_RUST_ARCHIVE}")
file(GLOB_RECURSE VOICE_RUST_FILES CONFIGURE_DEPENDS "${VOICE_RUST_SOURCE}/src/*.rs")
add_custom_command(OUTPUT "${VOICE_RUST_OUTPUT}"
  COMMAND "${VOICE_CARGO}" build --release --locked --target "${VOICE_RUST_TARGET}" --target-dir "${CMAKE_CURRENT_BINARY_DIR}/rust"
  WORKING_DIRECTORY "${VOICE_RUST_SOURCE}"
  DEPENDS ${VOICE_RUST_FILES} "${VOICE_RUST_SOURCE}/Cargo.toml" "${VOICE_RUST_SOURCE}/Cargo.lock"
    "${VOICE_RUST_SOURCE}/rust-toolchain.toml" "${VOICE_RUST_SOURCE}/../privacy/redactors.json"
  VERBATIM)
add_custom_target(voice-core-build DEPENDS "${VOICE_RUST_OUTPUT}")
add_library(voice-core STATIC IMPORTED GLOBAL)
set_target_properties(voice-core PROPERTIES IMPORTED_LOCATION "${VOICE_RUST_OUTPUT}")
add_dependencies(voice-core voice-core-build)
if(WIN32)
  target_link_libraries(voice-core INTERFACE ws2_32 bcrypt userenv ntdll advapi32)
elseif(APPLE)
  target_link_libraries(voice-core INTERFACE "-framework Security" "-framework CoreFoundation")
else()
  target_link_libraries(voice-core INTERFACE ${CMAKE_DL_LIBS} pthread m)
endif()
if(BUILD_TESTING)
  add_test(NAME voice-rust-core COMMAND "${VOICE_CARGO}" test --release --locked --target "${VOICE_RUST_TARGET}" --target-dir "${CMAKE_CURRENT_BINARY_DIR}/rust")
  set_tests_properties(voice-rust-core PROPERTIES WORKING_DIRECTORY "${VOICE_RUST_SOURCE}" TIMEOUT 120)
endif()
