// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// AUTO-GENERATED by scripts/gen-redactors.mts. Do not edit.
#pragma once
#include <string_view>
namespace voice::privacy {
struct Definition { const char* name; std::u16string_view pattern; bool ignoreCase; std::u16string_view replacement; };
inline constexpr std::u16string_view placeholder = uR"tm([redacted])tm";
inline constexpr Definition definitions[] = {
    {"json-web-token", uR"tm((^|[^A-Za-z0-9_-])eyJ[A-Za-z0-9_-]+\.eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)tm", false, uR"tm($1[redacted])tm"},
    {"bearer-token", uR"tm((^|[^A-Za-z0-9_])(Bearer[\s]+)[A-Za-z0-9._~+/=-]{16}[A-Za-z0-9._~+/=-]*)tm", true, uR"tm($1$2[redacted])tm"},
    {"address-password", uR"tm((://[^\s/:@]*:)[^\s/]+(@))tm", false, uR"tm($1[redacted]$2)tm"},
    {"named-value", uR"tm(((?:password|passwd|pwd|passphrase|secret[_-]?key|secret|token|api[_-]?key|access[_-]?key|private[_-]?key|credentials?)["']?[\s]*[=:][\s]*["']?)(?=[^\s"']{0,200}[0-9])[^\s"']{6}[^\s"']*)tm", true, uR"tm($1[redacted])tm"},
    {"api-key-sk", uR"tm((^|[^A-Za-z0-9_])sk-[A-Za-z0-9_-]{16}[A-Za-z0-9_-]*)tm", false, uR"tm($1[redacted])tm"},
    {"payment-key", uR"tm((^|[^A-Za-z0-9_])(?:sk|rk|pk)_(?:live|test)_[A-Za-z0-9]{16}[A-Za-z0-9]*)tm", false, uR"tm($1[redacted])tm"},
    {"webhook-secret", uR"tm((^|[^A-Za-z0-9_])whsec_[A-Za-z0-9]{16}[A-Za-z0-9]*)tm", false, uR"tm($1[redacted])tm"},
    {"github-token", uR"tm((^|[^A-Za-z0-9_])gh[pousr]_[A-Za-z0-9]{16}[A-Za-z0-9]*)tm", false, uR"tm($1[redacted])tm"},
    {"github-fine-grained-token", uR"tm((^|[^A-Za-z0-9_])github_pat_[A-Za-z0-9_]{16}[A-Za-z0-9_]*)tm", false, uR"tm($1[redacted])tm"},
    {"gitlab-token", uR"tm((^|[^A-Za-z0-9_])glpat-[A-Za-z0-9_-]{16}[A-Za-z0-9_-]*)tm", false, uR"tm($1[redacted])tm"},
    {"aws-access-key-id", uR"tm((^|[^A-Za-z0-9_])(?:AKIA|ASIA)[0-9A-Z]{16}(?![A-Za-z0-9_]))tm", false, uR"tm($1[redacted])tm"},
    {"google-api-key", uR"tm((^|[^A-Za-z0-9_])AIza[0-9A-Za-z_-]{35}(?![A-Za-z0-9_-]))tm", false, uR"tm($1[redacted])tm"},
    {"slack-token", uR"tm((^|[^A-Za-z0-9_])xox[abeprs]-[A-Za-z0-9-]{16}[A-Za-z0-9-]*)tm", false, uR"tm($1[redacted])tm"},
    {"npm-token", uR"tm((^|[^A-Za-z0-9_])npm_[A-Za-z0-9]{16}[A-Za-z0-9]*)tm", false, uR"tm($1[redacted])tm"},
    {"hugging-face-token", uR"tm((^|[^A-Za-z0-9_])hf_[A-Za-z0-9]{16}[A-Za-z0-9]*)tm", false, uR"tm($1[redacted])tm"},
    {"private-key-block", uR"tm(-----BEGIN [A-Z0-9 ]{0,40}PRIVATE KEY[A-Z ]{0,40}-----(?:[A-Za-z0-9+/=\s\\]*-----END [A-Z0-9 ]{0,40}PRIVATE KEY[A-Z ]{0,40}-----|[A-Za-z0-9+/=\s\\]*))tm", false, uR"tm([redacted])tm"},
};
}
