// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Writes each platform helper's list of redactors from native/shared/privacy/redactors.json, the one
// definition of what looks like a secret in text read off the screen (ADR-DESK-046), so that every
// helper applies the same patterns in the same order. A platform's helper adds its target here.
// Runs with the registries before every build, typecheck and test run (`npm run gen:redactors`);
// `--check` only says whether the files are current.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..");
export const redactorsPath = join(root, "native/shared/privacy/redactors.json");

export interface Redactor {
  name: string;
  description: string;
  pattern: string;
  ignoreCase: boolean;
  /** What a match becomes, with the placeholder filled in: `$1`, `$2` are the pattern's groups. */
  replacement: string;
}

/** The redactors as redactors.json has them, in order; throws on one it can't read, on a repeated
 * name, and on a pattern outside what every helper's regex engine reads the same way. */
export function redactorDefinitions(json = readFileSync(redactorsPath, "utf8")): { placeholder: string; redactors: Redactor[] } {
  const { placeholder, redactors } = JSON.parse(json) as { placeholder?: unknown; redactors?: unknown };
  if (typeof placeholder !== "string" || placeholder === "" || /[$\\]/.test(placeholder)) throw new Error("redactors.json: `placeholder` must be text without $ or \\");
  if (!Array.isArray(redactors) || redactors.length === 0) throw new Error("redactors.json: `redactors` must list at least one");
  const names = new Set<string>();
  const read = redactors.map((value: unknown): Redactor => {
    const { name, description, pattern, ignoreCase, replacement } = (value ?? {}) as Record<string, unknown>;
    if (typeof name !== "string" || !/^[a-z][a-z0-9-]*$/.test(name)) throw new Error(`redactors.json: a redactor's name must be lowercase words joined by hyphens (${String(name)})`);
    if (names.has(name)) throw new Error(`redactors.json: the name "${name}" is used twice`);
    names.add(name);
    if (typeof description !== "string" || description === "") throw new Error(`redactors.json: "${name}" needs a description`);
    if (typeof pattern !== "string" || typeof ignoreCase !== "boolean" || typeof replacement !== "string") {
      throw new Error(`redactors.json: "${name}" needs pattern, ignoreCase and replacement`);
    }
    // Lookbehind, named groups, Unicode classes, inline flags, possessive and atomic groups, and
    // backreferences are not read alike by ICU, ECMAScript and PCRE. Nor are \b, \w and \d: ICU
    // counts every script's letters and digits, ECMAScript only ASCII's.
    if (/\(\?<|\\[pPkKGAzZbBwWdD]|\(\?[a-zA-Z]|\(\?>|[*+?}]\+|\\[1-9]/.test(pattern)) throw new Error(`redactors.json: "${name}" uses regex syntax the helpers don't share`);
    // ICU runs these with a stack frame per repetition, and gives up on a long run, matching nothing
    // after it: `[..]{16}[..]*` and `[\\s]*` are run as one loop.
    if (/\{[0-9]+,\}|\\s[*+]/.test(pattern)) throw new Error(`redactors.json: "${name}" uses an open-ended count or a repeated \\s outside a class, which the helpers' engine gives up on`);
    // An empty alternative matches the empty text, which shows how many groups the pattern has.
    const groups = (new RegExp(`${pattern}|`, ignoreCase ? "i" : "").exec("")?.length ?? 1) - 1;
    for (const [, group] of replacement.matchAll(/\$([0-9]+)/g)) {
      if (Number(group) < 1 || Number(group) > groups) throw new Error(`redactors.json: "${name}"'s replacement names group ${group}, and its pattern has ${groups}`);
    }
    if (!replacement.includes("{placeholder}")) throw new Error(`redactors.json: "${name}"'s replacement must hold {placeholder}`);
    return { name, description, pattern, ignoreCase, replacement: replacement.replaceAll("{placeholder}", placeholder) };
  });
  return { placeholder, redactors: read };
}

/** `text` as a Swift raw string literal. */
function swiftLiteral(text: string): string {
  let hashes = "#";
  while (text.includes(`"${hashes}`) || text.includes(`\\${hashes}`)) hashes += "#";
  return `${hashes}"${text}"${hashes}`;
}

/** Redactors.generated.swift as it should read. */
export function swiftRedactors(json?: string): string {
  const { placeholder, redactors } = redactorDefinitions(json);
  return `// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// AUTO-GENERATED by scripts/gen-redactors.mts from native/shared/privacy/redactors.json. Do not
// edit: change redactors.json, then \`npm run gen:redactors\`.

extension Redactor {
    /// What replaces text that looks like a secret.
    static let placeholder = ${swiftLiteral(placeholder)}

    /// Every redactor, in the order they are applied.
    static let all: [Redactor] = [
${redactors
  .map(
    (redactor) => `        // ${redactor.description}
        Redactor(name: ${swiftLiteral(redactor.name)}, pattern: ${swiftLiteral(redactor.pattern)}, ignoreCase: ${redactor.ignoreCase}, replacement: ${swiftLiteral(redactor.replacement)}),`,
  )
  .join("\n")}
    ]
}
`;
}

/** C++ UTF-16 raw strings keep the shared regex syntax unchanged. */
function cppLiteral(text: string): string {
  let delimiter = "tm";
  while (text.includes(`)${delimiter}"`)) delimiter += "x";
  return `uR"${delimiter}(${text})${delimiter}"`;
}

export function windowsRedactors(json?: string): string {
  const { placeholder, redactors } = redactorDefinitions(json);
  return `// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// AUTO-GENERATED by scripts/gen-redactors.mts. Do not edit.
#pragma once
#include <string_view>
namespace voice::privacy {
struct Definition { const char* name; std::u16string_view pattern; bool ignoreCase; std::u16string_view replacement; };
inline constexpr std::u16string_view placeholder = ${cppLiteral(placeholder)};
inline constexpr Definition definitions[] = {
${redactors.map((r) => `    {"${r.name}", ${cppLiteral(r.pattern)}, ${r.ignoreCase}, ${cppLiteral(r.replacement)}},`).join("\n")}
};
}
`;
}

/** Each generated file's path, and what it should hold. */
export function generatedRedactors(): { path: string; contents: string }[] {
  return [
    { path: join(root, "native/macos/Sources/VoiceMacOSKit/Privacy/Redactors.generated.swift"), contents: swiftRedactors() },
    { path: join(root, "native/windows/src/Privacy/Redactors.generated.h"), contents: windowsRedactors() },
  ];
}

if (import.meta.main) {
  for (const { path, contents } of generatedRedactors()) {
    const current = existsSync(path) ? readFileSync(path, "utf8") : "";
    if (current === contents) continue;
    if (process.argv.includes("--check")) {
      process.stderr.write(`${path} is out of date: run \`npm run gen:redactors\`\n`);
      process.exit(1);
    }
    writeFileSync(path, contents);
    process.stdout.write(`Wrote ${path}\n`);
  }
}
