// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Writes src/core/agent/connectors/registry.ts, the list of the connectors, from the
// `export const … = defineConnector({ id: "…", order: … })` declarations in that folder, as the
// backend's scripts/gen-registries.mjs writes its tool registries: a new connector is one new file,
// with nothing else to remember (ADR-DESK-044). Runs before every build, typecheck and test run
// (`npm run gen:registries`); `--check` only says whether the file is current.

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..");
const folder = join(root, "src/core/agent/connectors");
const registryFile = "registry.ts";

interface Declaration {
  constant: string;
  id: string;
  order: number;
  file: string;
}

/** The connectors declared in `directory`'s files, in order; throws on a declaration it can't read,
 * and on a repeated id or order. */
export function connectorDeclarations(directory = folder): Declaration[] {
  const declarations: Declaration[] = [];
  for (const file of readdirSync(directory).filter((name) => name.endsWith(".ts") && name !== registryFile).sort()) {
    const source = readFileSync(join(directory, file), "utf8");
    const calls = source.split("defineConnector({").length - 1;
    const found = [...source.matchAll(/^export const (\w+) = defineConnector\(\{\n {2}id: "([a-z]+)",\n {2}order: (\d+),$/gm)];
    if (found.length !== calls) {
      throw new Error(`${file}: every defineConnector call must read \`export const name = defineConnector({\`, then \`id: "…",\` and \`order: …,\` on the next lines`);
    }
    for (const [, constant = "", id = "", order = ""] of found) declarations.push({ constant, id, order: Number(order), file });
  }
  declarations.sort((a, b) => a.order - b.order);
  for (const [index, declaration] of declarations.entries()) {
    const earlier = declarations.slice(0, index);
    if (earlier.some((other) => other.id === declaration.id)) throw new Error(`connector id "${declaration.id}" is declared twice`);
    if (earlier.some((other) => other.order === declaration.order)) throw new Error(`connector order ${declaration.order} is used twice`);
  }
  return declarations;
}

/** registry.ts as it should read, for the connectors in `directory`. */
export function connectorRegistry(directory = folder): string {
  const declarations = connectorDeclarations(directory);
  const byFile = new Map<string, string[]>();
  for (const { file, constant } of declarations) byFile.set(file, [...(byFile.get(file) ?? []), constant]);
  const imports = [...byFile]
    .sort(([a], [b]) => (a < b ? -1 : 1))
    .map(([file, constants]) => `import { ${[...constants].sort().join(", ")} } from "./${file.replace(/\.ts$/, ".js")}";`);
  return `// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// AUTO-GENERATED by scripts/gen-registries.mts from the defineConnector declarations in this
// folder. Do not edit: add or change a connector in its own file, then \`npm run gen:registries\`.

import type { Connector } from "./contract.js";
${imports.join("\n")}

/** Every connector's id. */
export type ConnectorID = ${declarations.map(({ id }) => `"${id}"`).join(" | ")};

/** The connectors, in their order (\`Connector.order\`): their switches' and bubbles'. */
export const connectors: readonly Connector[] = [${declarations.map(({ constant }) => constant).join(", ")}];
`;
}

if (import.meta.main) {
  const path = join(folder, registryFile);
  const current = existsSync(path) ? readFileSync(path, "utf8") : "";
  const wanted = connectorRegistry();
  if (process.argv.includes("--check")) {
    if (current !== wanted) {
      process.stderr.write(`${registryFile} is out of date: run \`npm run gen:registries\`\n`);
      process.exit(1);
    }
  } else if (current !== wanted) {
    writeFileSync(path, wanted);
    process.stdout.write(`Wrote ${registryFile}\n`);
  }
}
