// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// AUTO-GENERATED by scripts/gen-registries.mts from the defineConnector declarations in this
// folder. Do not edit: add or change a connector in its own file, then `npm run gen:registries`.

import type { Connector } from "./contract.js";
import { calendarConnector, remindersConnector } from "./calendar.js";
import { contactsConnector } from "./contacts.js";
import { emailConnector } from "./email.js";
import { filesConnector } from "./files.js";
import { messagesConnector } from "./macos/messages.js";
import { notesConnector } from "./macos/notes.js";
import { webConnector } from "./web.js";

/** Every connector's id. */
export type ConnectorID = "calendar" | "reminders" | "contacts" | "files" | "email" | "notes" | "messages" | "web";

/** The connectors, in their order (`Connector.order`): their switches' and bubbles'. */
export const connectors: readonly Connector[] = [calendarConnector, remindersConnector, contactsConnector, filesConnector, emailConnector, notesConnector, messagesConnector, webConnector];
